// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp1.Data;

namespace WebApp1.Migrations
{
    [DbContext(typeof(OutcomesContext))]
    partial class OutcomesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("WebApp1.Models.CourseLearningOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompleteLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Course")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseLearningOutcomeDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructor")
                        .HasColumnType("TEXT");

                    b.Property<int>("NotMeasurable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotMet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SatisfactoryLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CourseLearningOutcome");
                });

            modelBuilder.Entity("WebApp1.Models.StudentOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompleteLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Course")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructor")
                        .HasColumnType("TEXT");

                    b.Property<int>("NotMeasurable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotMet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SatisfactoryLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentOutcomeDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StudentOutcome");
                });
#pragma warning restore 612, 618
        }
    }
}
